[package]
name = "reader"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.22.0"

aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3control = "1.51.0"
tokio = { version = "1", features = ["full"] }