name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Writer Docker Image
      working-directory: ./writer
      run: |
        docker build -t writer-gh .
        docker tag writer-gh ali454/writer-gh

    - name: Build Reader Docker Image
      working-directory: ./reader
      run: |
        docker build -t reader-gh .
        docker tag reader-gh ali454/reader-gh
        
    - name: Push to Docker Registry
      # Replace the following with your Docker registry credentials and image name
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        WRITE_IMAGE_NAME: writer-gh
        READ_IMAGE_NAME: reader-gh

      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_USERNAME/$WRITE_IMAGE_NAME
        docker push $DOCKER_USERNAME/$READ_IMAGE_NAME