name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Openresty Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      working-directory: ./openresty
      run: |
        docker build -t openresty-gh .
        docker tag openresty-gh $DOCKER_USERNAME/openresty-gh

    - name: Build Consistent hashing server Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      working-directory: ./consistent_hashing_server
      run: |
        docker build -t consistent-hashing-server-gh .
        docker tag consistent-hashing-server-gh $DOCKER_USERNAME/consistent-hashing-server-gh


    - name: Push to Docker Registry
      # Replace the following with your Docker registry credentials and image name
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        OPENRESTY_IMAGE_NAME: openresty-gh
        CONSISTENT_HASHING_SERVER_IMAGE_NAME: consistent-hashing-server-gh

      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_USERNAME/$OPENRESTY_IMAGE_NAME
        docker push $DOCKER_USERNAME/$CONSISTENT_HASHING_SERVER_IMAGE_NAME